id: IEE718A79
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T23:09:18+00:00'
last_modified: '2022-06-09T06:42:27.066662+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16673
  title: ཀློང་སྙིང་སྒྲུབ་མཆོད་ལས་འགྲིག་དང་དཔེ་རིས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8437':
      image_group_id: I2PD18156
      title: Volume 1 of klong snying sgrub mchod las 'grig dang dpe ris/
      total_pages: 286
      order: 1
      base_file: 8437.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
