id: P007860
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG16673
  title: ཀློང་སྙིང་སྒྲུབ་མཆོད་ལས་འགྲིག་དང་དཔེ་རིས།
  author: ''
  volumes:
    cf55bad4300241799c7f04503be61a76:
      image_group_id: I2PD18156
      title: Volume 1 of klong snying sgrub mchod las 'grig dang dpe ris/
      volume_number: 1
      total_pages: 286
      base_file: v001.txt
