id: P007860
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16673
  title: ཀློང་སྙིང་སྒྲུབ་མཆོད་ལས་འགྲིག་དང་དཔེ་རིས།
  author: ''
  volumes:
    379bc8a0c7654182b954928ca0dba7bf:
      image_group_id: I2PD18156
      title: ''
      volume_number: 1
      total_pages: 286
ebook_metadata:
  title: ཀློང་སྙིང་སྒྲུབ་མཆོད་ལས་འགྲིག་དང་དཔེ་རིས།
  author: ''
  sku: P007860
  cover: cover.jpg
  layers:
  - pagination
